<streams>
<immutable_stream name="input"
                  type="input"
                  filename_template="base_mesh.nc"
                  filename_interval="none"
                  input_interval="initial_only" />

<immutable_stream name="restart"
                  type="input;output"
                  filename_template="restart.$Y-$M-$D_$h.$m.$s.nc"
                  filename_interval="00_00:00:01"
                  input_interval="initial_only"
                  output_interval="none" />

<stream name="output"
        type="output"
        filename_template="output.nc"
        clobber_mode="truncate"
        filename_interval="none"
        output_interval= "00:05:00">

	<var name="xtime"/>
	<var name="u"/>
	<var name="h"/>
	<var name="tracers"/>
	<var name="v"/>
	<var name="divergence"/>
	<var name="vorticity"/>
	<var name="vorticity_cell"/>
	<var name="pv_edge"/>
	<var name="h_edge"/>
	<var name="ke"/>
	<var name="pv_vertex"/>
	<var name="pv_cell"/>
	<var name="uReconstructX"/>
	<var name="uReconstructY"/>
	<var name="uReconstructZ"/>
	<var name="uReconstructZonal"/>
	<var name="uReconstructMeridional"/>
	<var name="latCell"/>
	<var name="lonCell"/>
	<var name="xCell"/>
	<var name="yCell"/>
	<var name="zCell"/>
	<var name="indexToCellID"/>
	<var name="latEdge"/>
	<var name="lonEdge"/>
	<var name="xEdge"/>
	<var name="yEdge"/>
	<var name="zEdge"/>
	<var name="indexToEdgeID"/>
	<var name="latVertex"/>
	<var name="lonVertex"/>
	<var name="xVertex"/>
	<var name="yVertex"/>
	<var name="zVertex"/>
	<var name="indexToVertexID"/>
	<var name="meshDensity"/>
	<var name="meshScalingDel2"/>
	<var name="meshScalingDel4"/>
	<var name="cellsOnEdge"/>
	<var name="nEdgesOnCell"/>
	<var name="nEdgesOnEdge"/>
	<var name="edgesOnCell"/>
	<var name="edgesOnEdge"/>
	<var name="weightsOnEdge"/>
	<var name="dvEdge"/>
	<var name="dcEdge"/>
	<var name="angleEdge"/>
	<var name="areaCell"/>
	<var name="areaTriangle"/>
	<var name="edgeNormalVectors"/>
	<var name="localVerticalUnitVectors"/>
	<var name="cellTangentPlane"/>
	<var name="cellsOnCell"/>
	<var name="verticesOnCell"/>
	<var name="verticesOnEdge"/>
	<var name="edgesOnVertex"/>
	<var name="cellsOnVertex"/>
	<var name="kiteAreasOnVertex"/>
	<var name="fEdge"/>
	<var name="fVertex"/>
	<var name="fCell"/>
	<var name="h_s"/>
	<var name="deriv_two"/>
	<var name="boundaryEdge"/>
	<var name="boundaryVertex"/>
	<var name="boundaryCell"/>
	<var name="u_src"/>
        <var name="cellsInLTSHalo"/>
        <var name="LTSRegionLocal"/>
        <var name="LTSRegion"/>
        <var name="mpiRankCell"/>
        <var name="blockPartitionCell"/>
</stream>

</streams>
